### ISSUE TITLE
How do you generate the text?

### ISSUE THREAD

**Issue by TiankaiHang** [Yutong-Zhou-cv/FFHQ-Text_Dataset#1]
Hi,

Thanks for your nice work!! How do you generate the text for the images? Do you ask other's help to write them? Or generate them using some pre-defined rule?

Best,
Tiankai

**Comment by Yutong-Zhou-cv** [comment]
> Hi,
> 
> Thanks for your nice work!! How do you generate the text for the images? Do you ask other's help to write them? Or generate them using some pre-defined rule?
> 
> Best, Tiankai

Hi Tiankai,
Thank you for your attention to our work.
This dataset was manually annotated following the basic facial terminology without others' help.
We are also considering a general way to generate more natural and diverse captions for images.

Have a nice day!

**Comment by TiankaiHang** [comment]
> 

Thanks for your reply~ How could I get the dataset? (I have filled the form for the request of the dataset)

**Comment by Yutong-Zhou-cv** [comment]
> > 
> 
> Thanks for your reply~ How could I get the dataset? (I have filled the form for the request of the dataset)

I have received your request~
I will send you an email with the FFHQ-Text dataset in the next several business days.
Thank you for your cooperation.

**Comment by TiankaiHang** [comment]
It's kind of you to do that!! Thanks a lot !!!
