### ISSUE TITLE
code

### ISSUE THREAD

**Issue by xu-pping** [Yutong-Zhou-cv/FFHQ-Text_Dataset#3]
Hello, thank you very much for sharing the dataset. I am very interested in this dataset. Do you have any code that matches this data set, FFHQ-Text?

**Comment by Yutong-Zhou-cv** [comment]
Hi @xu-pping! Thanks for your interest in our dataset. 
This dataset was not generated from code or extra packages for sentence generation. It was **manually annotated** following the basic facial terminology and knowledge.
If you want to check more details of our dataset, please fill out [this form](https://forms.gle/UCnuc6BDFVANraaM7) to request. Thanks:)

**Comment by xu-pping** [comment]
> Hi @xu-pping! Thanks for your interest in our dataset. This dataset was not generated from code or extra packages for sentence generation. It was **manually annotated** following the basic facial terminology and knowledge. If you want to check more details of our dataset, please fill out [this form](https://forms.gle/UCnuc6BDFVANraaM7) to request. Thanks:)

Thank you very much for your reply. I saw that you used this dataset in your paper: “CMAFGAN: A Cross-Modal Attention Fusion based Generative Adversarial Network for attribute word-to-face synthesis”. I would like to ask if you have the code to read this dataset?

**Comment by Yutong-Zhou-cv** [comment]
> Thank you very much for your reply. I saw that you used this dataset in your paper: “CMAFGAN: A Cross-Modal Attention Fusion based Generative Adversarial Network for attribute word-to-face synthesis”. I would like to ask if you have the code to read this dataset?

Thanks for the clarification. 
Firstly, this paper ([CMAFGAN](https://www.sciencedirect.com/science/article/pii/S0950705122008863)) is not mine and they didn't use our FFHQ-Text dataset but just mentioned it.
If you want to reach out to more papers with code (to train models using the FFHQ-Text dataset), please refer to [Awesome-Text-to-Image](https://github.com/Yutong-Zhou-cv/Awesome-Text-to-Image). There is also a subsection focus on [text-to-face](https://github.com/Yutong-Zhou-cv/awesome-Text-to-Image?tab=readme-ov-file#head-t2f) generation, which may be well for your needs. 
Thanks again for your contact.

**Comment by xu-pping** [comment]
> > Thank you very much for your reply. I saw that you used this dataset in your paper: “CMAFGAN: A Cross-Modal Attention Fusion based Generative Adversarial Network for attribute word-to-face synthesis”. I would like to ask if you have the code to read this dataset?
> 
> Thanks for the clarification. Firstly, this paper ([CMAFGAN](https://www.sciencedirect.com/science/article/pii/S0950705122008863)) is not mine and they didn't use our FFHQ-Text dataset but just mentioned it. If you want to reach out to more papers with code (to train models using the FFHQ-Text dataset), please refer to [Awesome-Text-to-Image](https://github.com/Yutong-Zhou-cv/Awesome-Text-to-Image). There is also a subsection focus on [text-to-face](https://github.com/Yutong-Zhou-cv/awesome-Text-to-Image?tab=readme-ov-file#head-t2f) generation, which may be well for your needs. Thanks again for your contact.

OK, thank you very much!
