### ISSUE TITLE
About dataset request

### ISSUE THREAD

**Issue by Oguzhanercan** [Yutong-Zhou-cv/FFHQ-Text_Dataset#4]
Hi, thanks for your work. I have sent an email about dataset access but did not get any response, can you share it with me?
My email adress is:
oguzhanercancs@gmail.com

**Comment by Yutong-Zhou-cv** [comment]
Hi @Oguzhanercan, Thanks for your interest in our dataset. I already replied to your email titled "About FFHQ-Text Dataset" on November 11th. Please check your spam folder if the above mail is not delivered to your inbox.
I also send the dataset to your provided new email.
If you have any further concerns, please feel free to contact me:)

**Comment by Oguzhanercan** [comment]
Sorry for that, I did not checked the spam folder. Thank you
